---
title: "Data Cleaning"
format: html
editor: visual
echo: false
---

## Load Packages

```{r}
library(tidyverse)
library(lubridate)
```

## Read in Raw Data

```{r}
raw <- read.csv("~/GitHub/lapd-crime-analysis/crima_analysis/data/raw/Crime_Data_from_2020_to_2024.csv")
```

## Review data

```{r}
summary(raw)
```

```{r}
clean <- raw %>%
  mutate(
    DATE.OCC = mdy_hms(DATE.OCC),
    Date.Rptd = as.Date(lubridate::mdy_hms(Date.Rptd))
    ) %>%
  distinct()
```

```{r}
clean <- clean %>%
  mutate(
    TIME.OCC = stringr::str_pad(TIME.OCC, width = 4, pad = "0"),
    TIME.OCC = lubridate::parse_date_time(TIME.OCC, orders = "HM"),
    TIME.OCC = format(TIME.OCC, "%H:%M")
    ) 
```


```{r}
#cleaning AREA.NAME to standardize
clean %>%
  mutate(
    AREA.NAME = stringr::str_squish(stringr::str_to_title(AREA.NAME))
  )
```

```{r}
crime_cat <- clean %>%
  mutate(
    Crm.Cd.Desc = case_when(
      Crm.Cd.Desc %in% c("BATTERY - SIMPLE ASSAULT",
                         "ASSAULT WITH DEADLY WEAPON",
                         "ROBBERY",
                         "HOMICIDE",
                         "RAPE, FORCIBLE") ~ "Violent",
      
      Crm.Cd.Desc %in% c("BURGLARY",
                         "THEFT OF IDENTITY",
                         "GRAND THEFT AUTO",
                         "PETTY THEFT",
                         "VANDALISM") ~ "Property",
      
      TRUE ~ "Other"
    )
  )
```

```{r}
clean <- crime_cat %>%
  distinct(DR_NO, .keep_all = TRUE)
```

```{r}
clean <- clean %>%
  select(AREA, AREA.NAME, Crm.Cd.Desc, DATE.OCC)
```





